name: Publish
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -L https://api.github.com/repos/${{ github.repository }}/tarball/v0.1.0 > source.tar.gz
      - uses: filecoin-station/publish-zinnia-module-action@v0
        with:
          source: source.tar.gz
          w3up-private-key: ${{ secrets.W3UP_PRIVATE_KEY }}
          w3up-proof: ${{ secrets.W3UP_PROOF }}
          w3name-private-key: ${{ secrets.W3NAME_PRIVATE_KEY }}
          w3name-revision: ${{ secrets.W3NAME_REVISION }}
